"""Build scripts/blc/mobdata.lua from the game's scripts: for each mob prefab, the animation its
attack starts with, the frame its hit lands on (DoAttack), and its attack period (TUNING key or
seconds). Heuristic parse; only entries where both the animation and the frame were found."""
import re, os, sys
GS = sys.argv[1]
OUT = sys.argv[2]

def read(p):
    return open(p, encoding="utf-8", errors="replace").read()

def hit_frame(block):
    events = [(m.start(), int(m.group(1))) for m in re.finditer(r"TimeEvent\(\s*(\d+)\s*\*\s*FRAMES", block)]
    for i, (pos, n) in enumerate(events):
        end = events[i + 1][0] if i + 1 < len(events) else len(block)
        if "DoAttack" in block[pos:end]:
            return n
    return None

def table_at(text, start):
    """the {...} starting at text[start] == '{'"""
    depth = 0
    for i in range(start, len(text)):
        if text[i] == "{": depth += 1
        elif text[i] == "}":
            depth -= 1
            if depth == 0: return text[start:i + 1]
    return text[start:]

def sg_attack(text):
    # an explicit attack state
    m = re.search(r'name\s*=\s*"attack"\s*,', text)
    if m:
        st = text.rfind("State", 0, m.start())
        nxt = re.search(r"\bState\s*\{", text[m.end():])
        block = text[st: m.end() + (nxt.start() if nxt else len(text) - m.end())]
        anim = re.search(r'PlayAnimation\(\s*"([\w]+)"', block)
        n = hit_frame(block)
        if anim and n is not None:
            return anim.group(1), n
    # CommonStates.AddCombatStates(states, { attacktimeline = ... }, { attack = "..." })
    m = re.search(r"CommonStates\.AddCombatStates\s*\(", text)
    if m:
        args = text[m.end(): m.end() + 6000]
        tl = re.search(r"attacktimeline\s*=\s*(\{|[A-Za-z_]\w*)", args)
        if tl:
            if tl.group(1) == "{":
                block = table_at(args, tl.start(1))
            else:
                d = re.search(r"local\s+" + re.escape(tl.group(1)) + r"\s*=\s*\{", text)
                block = table_at(text, d.end() - 1) if d else ""
            n = hit_frame(block)
            an = re.search(r'\battack\s*=\s*"([\w]+)"', args[: 3000])
            if n is not None:
                return (an.group(1) if an else "atk"), n
    return None

sgs = {}
for f in os.listdir(os.path.join(GS, "stategraphs")):
    if f.startswith("SG") and f.endswith(".lua"):
        r = sg_attack(read(os.path.join(GS, "stategraphs", f)))
        if r: sgs[f[:-4]] = r

mobs = {}
for f in sorted(os.listdir(os.path.join(GS, "prefabs"))):
    if not f.endswith(".lua"): continue
    text = read(os.path.join(GS, "prefabs", f))
    # the stategraph set most often in the file (pigman: SGpig twice, SGwerepig and SGmoonpig once)
    calls = re.findall(r'SetStateGraph\((.*)', text) # to the end of the line: nested brackets
    graphs = [g for c in calls for g in re.findall(r'"(SG\w+)"', c)]
    if not graphs: continue
    counts = {g: graphs.count(g) for g in set(graphs)}
    top = max(counts.values())
    best = [g for g, c in counts.items() if c == top]
    if len(best) != 1: continue
    sg = best[0]
    if sg not in sgs: continue
    names = re.findall(r'(?<![\w.])Prefab\(\s*"([\w]+)"', text) or [f[:-4]]
    period = re.search(r"SetAttackPeriod\(\s*(TUNING\.\w+|[\d.]+)", text)
    p = period.group(1) if period else None
    # combat:SetRange(attack[, hit]): the hit range is what the server checks when the blow lands
    # (one call in the file only: several prefabs with their own ranges can't be told apart here,
    # then the attack range the game sends with each mob is used)
    rngs = re.findall(r"combat:SetRange\(\s*(TUNING\.\w+|[\d.]+)\s*(?:,\s*(TUNING\.\w+|[\d.]+))?", text)
    r = (rngs[0][1] or rngs[0][0]) if len(rngs) == 1 else None
    for name in names:
        if name.endswith("_placer") or "fx" in name: continue
        mobs[name] = (sgs[sg][0], sgs[sg][1], p, sg, r)

with open(OUT, "w") as o:
    o.write("-- Generated by tools/mobdata.py from the game's stategraphs and prefabs: for each mob, the\n")
    o.write("-- animation its attack starts with, the frame its hit lands on, its attack period. Do not edit.\n")
    o.write("return {\n")
    for name in sorted(mobs):
        anim, n, p, sg, r = mobs[name]
        val = lambda v: ("\"%s\"" % v[7:]) if v and v.startswith("TUNING.") else (v if v else "nil")
        o.write('    %s = { anim = "%s", hit = %d, period = %s, range = %s }, -- %s\n' % (name, anim, n, val(p), val(r), sg))
    o.write("}\n")
print(len(sgs), "stategraphs with an attack,", len(mobs), "mobs")
for k in ["pigman", "killerbee", "bee", "tallbird", "spider", "spider_warrior", "hound", "merm", "beefalo", "frog", "spiderqueen", "deerclops", "bunnyman", "knight", "bishop", "rook", "tentacle", "mosquito", "bat", "walrus", "krampus", "koalefant_summer", "monkey", "slurper"]:
    print("  ", k, mobs.get(k)) if k in ("spider", "pigman", "tallbird", "killerbee", "spider_warrior") else None
